// Songs: { id, title, difficulty, bpm, notes: [{midi, hand, beat, length}] }
// hand: 'R' = right, 'L' = left. beat/length in quarter notes.
// Keyboard range: C3 (48) -> C5 (72).

const SONGS = [
  // ----------------------------- VERY EASY -----------------------------
  {
    id: 'au-clair',
    title: 'Au clair de la lune',
    difficulty: 'very-easy',
    bpm: 90,
    notes: [
      // Phrase 1 — Au clair de la lune, mon ami Pierrot
      { midi: 60, hand: 'R', beat: 0,  length: 1 },
      { midi: 60, hand: 'R', beat: 1,  length: 1 },
      { midi: 60, hand: 'R', beat: 2,  length: 1 },
      { midi: 62, hand: 'R', beat: 3,  length: 1 },
      { midi: 64, hand: 'R', beat: 4,  length: 2 },
      { midi: 62, hand: 'R', beat: 6,  length: 2 },
      { midi: 60, hand: 'R', beat: 8,  length: 1 },
      { midi: 64, hand: 'R', beat: 9,  length: 1 },
      { midi: 62, hand: 'R', beat: 10, length: 1 },
      { midi: 62, hand: 'R', beat: 11, length: 1 },
      { midi: 60, hand: 'R', beat: 12, length: 4 },
      // Phrase 2 — Prête-moi ta plume, pour écrire un mot (idem)
      { midi: 60, hand: 'R', beat: 16, length: 1 },
      { midi: 60, hand: 'R', beat: 17, length: 1 },
      { midi: 60, hand: 'R', beat: 18, length: 1 },
      { midi: 62, hand: 'R', beat: 19, length: 1 },
      { midi: 64, hand: 'R', beat: 20, length: 2 },
      { midi: 62, hand: 'R', beat: 22, length: 2 },
      { midi: 60, hand: 'R', beat: 24, length: 1 },
      { midi: 64, hand: 'R', beat: 25, length: 1 },
      { midi: 62, hand: 'R', beat: 26, length: 1 },
      { midi: 62, hand: 'R', beat: 27, length: 1 },
      { midi: 60, hand: 'R', beat: 28, length: 4 },
      // Phrase 3 — Ma chandelle est morte, je n'ai plus de feu
      { midi: 62, hand: 'R', beat: 32, length: 1 },
      { midi: 62, hand: 'R', beat: 33, length: 1 },
      { midi: 62, hand: 'R', beat: 34, length: 1 },
      { midi: 62, hand: 'R', beat: 35, length: 1 },
      { midi: 69, hand: 'R', beat: 36, length: 2 },
      { midi: 69, hand: 'R', beat: 38, length: 2 },
      { midi: 60, hand: 'R', beat: 40, length: 1 },
      { midi: 64, hand: 'R', beat: 41, length: 1 },
      { midi: 62, hand: 'R', beat: 42, length: 1 },
      { midi: 62, hand: 'R', beat: 43, length: 1 },
      { midi: 60, hand: 'R', beat: 44, length: 4 },
      // Phrase 4 — Ouvre-moi ta porte, pour l'amour de Dieu (idem phrase 1)
      { midi: 60, hand: 'R', beat: 48, length: 1 },
      { midi: 60, hand: 'R', beat: 49, length: 1 },
      { midi: 60, hand: 'R', beat: 50, length: 1 },
      { midi: 62, hand: 'R', beat: 51, length: 1 },
      { midi: 64, hand: 'R', beat: 52, length: 2 },
      { midi: 62, hand: 'R', beat: 54, length: 2 },
      { midi: 60, hand: 'R', beat: 56, length: 1 },
      { midi: 64, hand: 'R', beat: 57, length: 1 },
      { midi: 62, hand: 'R', beat: 58, length: 1 },
      { midi: 62, hand: 'R', beat: 59, length: 1 },
      { midi: 60, hand: 'R', beat: 60, length: 4 },
      // Basse (do / sol / do / do par phrase)
      { midi: 48, hand: 'L', beat: 0,  length: 4 },
      { midi: 48, hand: 'L', beat: 4,  length: 4 },
      { midi: 55, hand: 'L', beat: 8,  length: 4 },
      { midi: 48, hand: 'L', beat: 12, length: 4 },
      { midi: 48, hand: 'L', beat: 16, length: 4 },
      { midi: 48, hand: 'L', beat: 20, length: 4 },
      { midi: 55, hand: 'L', beat: 24, length: 4 },
      { midi: 48, hand: 'L', beat: 28, length: 4 },
      { midi: 55, hand: 'L', beat: 32, length: 4 },
      { midi: 53, hand: 'L', beat: 36, length: 4 },
      { midi: 55, hand: 'L', beat: 40, length: 4 },
      { midi: 48, hand: 'L', beat: 44, length: 4 },
      { midi: 48, hand: 'L', beat: 48, length: 4 },
      { midi: 48, hand: 'L', beat: 52, length: 4 },
      { midi: 55, hand: 'L', beat: 56, length: 4 },
      { midi: 48, hand: 'L', beat: 60, length: 4 },
    ],
  },

  {
    id: 'twinkle',
    title: 'Ah ! vous dirai-je, maman (Twinkle)',
    difficulty: 'very-easy',
    bpm: 100,
    notes: [
      // Twinkle twinkle little star
      { midi: 60, hand: 'R', beat: 0,  length: 1 },
      { midi: 60, hand: 'R', beat: 1,  length: 1 },
      { midi: 67, hand: 'R', beat: 2,  length: 1 },
      { midi: 67, hand: 'R', beat: 3,  length: 1 },
      { midi: 69, hand: 'R', beat: 4,  length: 1 },
      { midi: 69, hand: 'R', beat: 5,  length: 1 },
      { midi: 67, hand: 'R', beat: 6,  length: 2 },
      // How I wonder what you are
      { midi: 65, hand: 'R', beat: 8,  length: 1 },
      { midi: 65, hand: 'R', beat: 9,  length: 1 },
      { midi: 64, hand: 'R', beat: 10, length: 1 },
      { midi: 64, hand: 'R', beat: 11, length: 1 },
      { midi: 62, hand: 'R', beat: 12, length: 1 },
      { midi: 62, hand: 'R', beat: 13, length: 1 },
      { midi: 60, hand: 'R', beat: 14, length: 2 },
      // Up above the world so high
      { midi: 67, hand: 'R', beat: 16, length: 1 },
      { midi: 67, hand: 'R', beat: 17, length: 1 },
      { midi: 65, hand: 'R', beat: 18, length: 1 },
      { midi: 65, hand: 'R', beat: 19, length: 1 },
      { midi: 64, hand: 'R', beat: 20, length: 1 },
      { midi: 64, hand: 'R', beat: 21, length: 1 },
      { midi: 62, hand: 'R', beat: 22, length: 2 },
      // Like a diamond in the sky
      { midi: 67, hand: 'R', beat: 24, length: 1 },
      { midi: 67, hand: 'R', beat: 25, length: 1 },
      { midi: 65, hand: 'R', beat: 26, length: 1 },
      { midi: 65, hand: 'R', beat: 27, length: 1 },
      { midi: 64, hand: 'R', beat: 28, length: 1 },
      { midi: 64, hand: 'R', beat: 29, length: 1 },
      { midi: 62, hand: 'R', beat: 30, length: 2 },
      // Reprise complète : Twinkle twinkle...
      { midi: 60, hand: 'R', beat: 32, length: 1 },
      { midi: 60, hand: 'R', beat: 33, length: 1 },
      { midi: 67, hand: 'R', beat: 34, length: 1 },
      { midi: 67, hand: 'R', beat: 35, length: 1 },
      { midi: 69, hand: 'R', beat: 36, length: 1 },
      { midi: 69, hand: 'R', beat: 37, length: 1 },
      { midi: 67, hand: 'R', beat: 38, length: 2 },
      { midi: 65, hand: 'R', beat: 40, length: 1 },
      { midi: 65, hand: 'R', beat: 41, length: 1 },
      { midi: 64, hand: 'R', beat: 42, length: 1 },
      { midi: 64, hand: 'R', beat: 43, length: 1 },
      { midi: 62, hand: 'R', beat: 44, length: 1 },
      { midi: 62, hand: 'R', beat: 45, length: 1 },
      { midi: 60, hand: 'R', beat: 46, length: 2 },
      // Basse : do – do – fa – do – sol – do – sol – do  (par mesure de 4)
      { midi: 48, hand: 'L', beat: 0,  length: 4 },
      { midi: 53, hand: 'L', beat: 4,  length: 4 },
      { midi: 53, hand: 'L', beat: 8,  length: 4 },
      { midi: 48, hand: 'L', beat: 12, length: 4 },
      { midi: 53, hand: 'L', beat: 16, length: 4 },
      { midi: 48, hand: 'L', beat: 20, length: 4 },
      { midi: 53, hand: 'L', beat: 24, length: 4 },
      { midi: 48, hand: 'L', beat: 28, length: 4 },
      { midi: 48, hand: 'L', beat: 32, length: 4 },
      { midi: 53, hand: 'L', beat: 36, length: 4 },
      { midi: 53, hand: 'L', beat: 40, length: 4 },
      { midi: 48, hand: 'L', beat: 44, length: 4 },
    ],
  },

  {
    id: 'mary-lamb',
    title: 'Mary had a little lamb',
    difficulty: 'very-easy',
    bpm: 100,
    notes: [
      // Mary had a little lamb
      { midi: 64, hand: 'R', beat: 0,  length: 1 },
      { midi: 62, hand: 'R', beat: 1,  length: 1 },
      { midi: 60, hand: 'R', beat: 2,  length: 1 },
      { midi: 62, hand: 'R', beat: 3,  length: 1 },
      { midi: 64, hand: 'R', beat: 4,  length: 1 },
      { midi: 64, hand: 'R', beat: 5,  length: 1 },
      { midi: 64, hand: 'R', beat: 6,  length: 2 },
      // little lamb, little lamb
      { midi: 62, hand: 'R', beat: 8,  length: 1 },
      { midi: 62, hand: 'R', beat: 9,  length: 1 },
      { midi: 62, hand: 'R', beat: 10, length: 2 },
      { midi: 64, hand: 'R', beat: 12, length: 1 },
      { midi: 67, hand: 'R', beat: 13, length: 1 },
      { midi: 67, hand: 'R', beat: 14, length: 2 },
      // Mary had a little lamb
      { midi: 64, hand: 'R', beat: 16, length: 1 },
      { midi: 62, hand: 'R', beat: 17, length: 1 },
      { midi: 60, hand: 'R', beat: 18, length: 1 },
      { midi: 62, hand: 'R', beat: 19, length: 1 },
      { midi: 64, hand: 'R', beat: 20, length: 1 },
      { midi: 64, hand: 'R', beat: 21, length: 1 },
      { midi: 64, hand: 'R', beat: 22, length: 1 },
      { midi: 64, hand: 'R', beat: 23, length: 1 },
      // its fleece was white as snow
      { midi: 62, hand: 'R', beat: 24, length: 1 },
      { midi: 62, hand: 'R', beat: 25, length: 1 },
      { midi: 64, hand: 'R', beat: 26, length: 1 },
      { midi: 62, hand: 'R', beat: 27, length: 1 },
      { midi: 60, hand: 'R', beat: 28, length: 4 },
      // Reprise
      { midi: 64, hand: 'R', beat: 32, length: 1 },
      { midi: 62, hand: 'R', beat: 33, length: 1 },
      { midi: 60, hand: 'R', beat: 34, length: 1 },
      { midi: 62, hand: 'R', beat: 35, length: 1 },
      { midi: 64, hand: 'R', beat: 36, length: 1 },
      { midi: 64, hand: 'R', beat: 37, length: 1 },
      { midi: 64, hand: 'R', beat: 38, length: 2 },
      { midi: 62, hand: 'R', beat: 40, length: 1 },
      { midi: 62, hand: 'R', beat: 41, length: 1 },
      { midi: 64, hand: 'R', beat: 42, length: 1 },
      { midi: 62, hand: 'R', beat: 43, length: 1 },
      { midi: 60, hand: 'R', beat: 44, length: 4 },
      // Basse
      { midi: 48, hand: 'L', beat: 0,  length: 4 },
      { midi: 48, hand: 'L', beat: 4,  length: 4 },
      { midi: 55, hand: 'L', beat: 8,  length: 4 },
      { midi: 48, hand: 'L', beat: 12, length: 4 },
      { midi: 48, hand: 'L', beat: 16, length: 4 },
      { midi: 55, hand: 'L', beat: 20, length: 4 },
      { midi: 55, hand: 'L', beat: 24, length: 4 },
      { midi: 48, hand: 'L', beat: 28, length: 4 },
      { midi: 48, hand: 'L', beat: 32, length: 4 },
      { midi: 48, hand: 'L', beat: 36, length: 4 },
      { midi: 55, hand: 'L', beat: 40, length: 4 },
      { midi: 48, hand: 'L', beat: 44, length: 4 },
    ],
  },

  // ----------------------------- EASY -----------------------------
  {
    id: 'frere-jacques',
    title: 'Frère Jacques',
    difficulty: 'easy',
    bpm: 110,
    notes: [
      // Frère Jacques (x2)
      { midi: 60, hand: 'R', beat: 0,  length: 1 },
      { midi: 62, hand: 'R', beat: 1,  length: 1 },
      { midi: 64, hand: 'R', beat: 2,  length: 1 },
      { midi: 60, hand: 'R', beat: 3,  length: 1 },
      { midi: 60, hand: 'R', beat: 4,  length: 1 },
      { midi: 62, hand: 'R', beat: 5,  length: 1 },
      { midi: 64, hand: 'R', beat: 6,  length: 1 },
      { midi: 60, hand: 'R', beat: 7,  length: 1 },
      // Dormez-vous (x2)
      { midi: 64, hand: 'R', beat: 8,  length: 1 },
      { midi: 65, hand: 'R', beat: 9,  length: 1 },
      { midi: 67, hand: 'R', beat: 10, length: 2 },
      { midi: 64, hand: 'R', beat: 12, length: 1 },
      { midi: 65, hand: 'R', beat: 13, length: 1 },
      { midi: 67, hand: 'R', beat: 14, length: 2 },
      // Sonnez les matines (x2)
      { midi: 67, hand: 'R', beat: 16, length: 0.5 },
      { midi: 69, hand: 'R', beat: 16.5, length: 0.5 },
      { midi: 67, hand: 'R', beat: 17, length: 0.5 },
      { midi: 65, hand: 'R', beat: 17.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 18, length: 1 },
      { midi: 60, hand: 'R', beat: 19, length: 1 },
      { midi: 67, hand: 'R', beat: 20, length: 0.5 },
      { midi: 69, hand: 'R', beat: 20.5, length: 0.5 },
      { midi: 67, hand: 'R', beat: 21, length: 0.5 },
      { midi: 65, hand: 'R', beat: 21.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 22, length: 1 },
      { midi: 60, hand: 'R', beat: 23, length: 1 },
      // Ding dang dong (x2)
      { midi: 60, hand: 'R', beat: 24, length: 1 },
      { midi: 55, hand: 'R', beat: 25, length: 1 },
      { midi: 60, hand: 'R', beat: 26, length: 2 },
      { midi: 60, hand: 'R', beat: 28, length: 1 },
      { midi: 55, hand: 'R', beat: 29, length: 1 },
      { midi: 60, hand: 'R', beat: 30, length: 2 },
      // Reprise (canon en solo : on rejoue tout)
      { midi: 60, hand: 'R', beat: 32, length: 1 },
      { midi: 62, hand: 'R', beat: 33, length: 1 },
      { midi: 64, hand: 'R', beat: 34, length: 1 },
      { midi: 60, hand: 'R', beat: 35, length: 1 },
      { midi: 60, hand: 'R', beat: 36, length: 1 },
      { midi: 62, hand: 'R', beat: 37, length: 1 },
      { midi: 64, hand: 'R', beat: 38, length: 1 },
      { midi: 60, hand: 'R', beat: 39, length: 1 },
      { midi: 64, hand: 'R', beat: 40, length: 1 },
      { midi: 65, hand: 'R', beat: 41, length: 1 },
      { midi: 67, hand: 'R', beat: 42, length: 2 },
      { midi: 64, hand: 'R', beat: 44, length: 1 },
      { midi: 65, hand: 'R', beat: 45, length: 1 },
      { midi: 67, hand: 'R', beat: 46, length: 2 },
      { midi: 67, hand: 'R', beat: 48, length: 0.5 },
      { midi: 69, hand: 'R', beat: 48.5, length: 0.5 },
      { midi: 67, hand: 'R', beat: 49, length: 0.5 },
      { midi: 65, hand: 'R', beat: 49.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 50, length: 1 },
      { midi: 60, hand: 'R', beat: 51, length: 1 },
      { midi: 67, hand: 'R', beat: 52, length: 0.5 },
      { midi: 69, hand: 'R', beat: 52.5, length: 0.5 },
      { midi: 67, hand: 'R', beat: 53, length: 0.5 },
      { midi: 65, hand: 'R', beat: 53.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 54, length: 1 },
      { midi: 60, hand: 'R', beat: 55, length: 1 },
      { midi: 60, hand: 'R', beat: 56, length: 1 },
      { midi: 55, hand: 'R', beat: 57, length: 1 },
      { midi: 60, hand: 'R', beat: 58, length: 2 },
      { midi: 60, hand: 'R', beat: 60, length: 1 },
      { midi: 55, hand: 'R', beat: 61, length: 1 },
      { midi: 60, hand: 'R', beat: 62, length: 2 },
      // Basse pédale do
      { midi: 48, hand: 'L', beat: 0,  length: 4 },
      { midi: 48, hand: 'L', beat: 4,  length: 4 },
      { midi: 48, hand: 'L', beat: 8,  length: 4 },
      { midi: 48, hand: 'L', beat: 12, length: 4 },
      { midi: 48, hand: 'L', beat: 16, length: 4 },
      { midi: 48, hand: 'L', beat: 20, length: 4 },
      { midi: 48, hand: 'L', beat: 24, length: 4 },
      { midi: 48, hand: 'L', beat: 28, length: 4 },
      { midi: 48, hand: 'L', beat: 32, length: 4 },
      { midi: 48, hand: 'L', beat: 36, length: 4 },
      { midi: 48, hand: 'L', beat: 40, length: 4 },
      { midi: 48, hand: 'L', beat: 44, length: 4 },
      { midi: 48, hand: 'L', beat: 48, length: 4 },
      { midi: 48, hand: 'L', beat: 52, length: 4 },
      { midi: 48, hand: 'L', beat: 56, length: 4 },
      { midi: 48, hand: 'L', beat: 60, length: 4 },
    ],
  },

  {
    id: 'jingle-bells',
    title: 'Jingle Bells',
    difficulty: 'easy',
    bpm: 130,
    notes: [
      // Dashing through the snow / In a one-horse open sleigh
      { midi: 64, hand: 'R', beat: 0,  length: 1 },
      { midi: 64, hand: 'R', beat: 1,  length: 1 },
      { midi: 64, hand: 'R', beat: 2,  length: 2 },
      { midi: 64, hand: 'R', beat: 4,  length: 1 },
      { midi: 64, hand: 'R', beat: 5,  length: 1 },
      { midi: 64, hand: 'R', beat: 6,  length: 2 },
      { midi: 64, hand: 'R', beat: 8,  length: 1 },
      { midi: 67, hand: 'R', beat: 9,  length: 1 },
      { midi: 60, hand: 'R', beat: 10, length: 1 },
      { midi: 62, hand: 'R', beat: 11, length: 1 },
      { midi: 64, hand: 'R', beat: 12, length: 4 },
      // O'er the fields we go / Laughing all the way
      { midi: 65, hand: 'R', beat: 16, length: 1 },
      { midi: 65, hand: 'R', beat: 17, length: 1 },
      { midi: 65, hand: 'R', beat: 18, length: 1 },
      { midi: 65, hand: 'R', beat: 19, length: 1 },
      { midi: 65, hand: 'R', beat: 20, length: 1 },
      { midi: 64, hand: 'R', beat: 21, length: 1 },
      { midi: 64, hand: 'R', beat: 22, length: 1 },
      { midi: 64, hand: 'R', beat: 23, length: 0.5 },
      { midi: 64, hand: 'R', beat: 23.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 24, length: 1 },
      { midi: 62, hand: 'R', beat: 25, length: 1 },
      { midi: 62, hand: 'R', beat: 26, length: 1 },
      { midi: 64, hand: 'R', beat: 27, length: 1 },
      { midi: 62, hand: 'R', beat: 28, length: 2 },
      { midi: 67, hand: 'R', beat: 30, length: 2 },
      // Refrain — Jingle bells, jingle bells, jingle all the way
      { midi: 64, hand: 'R', beat: 32, length: 1 },
      { midi: 64, hand: 'R', beat: 33, length: 1 },
      { midi: 64, hand: 'R', beat: 34, length: 2 },
      { midi: 64, hand: 'R', beat: 36, length: 1 },
      { midi: 64, hand: 'R', beat: 37, length: 1 },
      { midi: 64, hand: 'R', beat: 38, length: 2 },
      { midi: 64, hand: 'R', beat: 40, length: 1 },
      { midi: 67, hand: 'R', beat: 41, length: 1 },
      { midi: 60, hand: 'R', beat: 42, length: 1 },
      { midi: 62, hand: 'R', beat: 43, length: 1 },
      { midi: 64, hand: 'R', beat: 44, length: 4 },
      // Oh what fun it is to ride in a one-horse open sleigh
      { midi: 65, hand: 'R', beat: 48, length: 1 },
      { midi: 65, hand: 'R', beat: 49, length: 1 },
      { midi: 65, hand: 'R', beat: 50, length: 1 },
      { midi: 65, hand: 'R', beat: 51, length: 1 },
      { midi: 65, hand: 'R', beat: 52, length: 1 },
      { midi: 64, hand: 'R', beat: 53, length: 1 },
      { midi: 64, hand: 'R', beat: 54, length: 1 },
      { midi: 64, hand: 'R', beat: 55, length: 0.5 },
      { midi: 64, hand: 'R', beat: 55.5, length: 0.5 },
      { midi: 67, hand: 'R', beat: 56, length: 1 },
      { midi: 67, hand: 'R', beat: 57, length: 1 },
      { midi: 65, hand: 'R', beat: 58, length: 1 },
      { midi: 62, hand: 'R', beat: 59, length: 1 },
      { midi: 60, hand: 'R', beat: 60, length: 4 },
      // Basse — alternance do / sol
      { midi: 48, hand: 'L', beat: 0,  length: 4 },
      { midi: 48, hand: 'L', beat: 4,  length: 4 },
      { midi: 55, hand: 'L', beat: 8,  length: 4 },
      { midi: 48, hand: 'L', beat: 12, length: 4 },
      { midi: 53, hand: 'L', beat: 16, length: 4 },
      { midi: 48, hand: 'L', beat: 20, length: 4 },
      { midi: 55, hand: 'L', beat: 24, length: 4 },
      { midi: 48, hand: 'L', beat: 28, length: 4 },
      { midi: 48, hand: 'L', beat: 32, length: 4 },
      { midi: 48, hand: 'L', beat: 36, length: 4 },
      { midi: 55, hand: 'L', beat: 40, length: 4 },
      { midi: 48, hand: 'L', beat: 44, length: 4 },
      { midi: 53, hand: 'L', beat: 48, length: 4 },
      { midi: 48, hand: 'L', beat: 52, length: 4 },
      { midi: 55, hand: 'L', beat: 56, length: 4 },
      { midi: 48, hand: 'L', beat: 60, length: 4 },
    ],
  },

  {
    id: 'happy-birthday',
    title: 'Joyeux anniversaire',
    difficulty: 'easy',
    bpm: 100,
    notes: [
      // Joyeux a-nni-ver-sai-re
      { midi: 60, hand: 'R', beat: 0,    length: 0.75 },
      { midi: 60, hand: 'R', beat: 0.75, length: 0.25 },
      { midi: 62, hand: 'R', beat: 1,    length: 1 },
      { midi: 60, hand: 'R', beat: 2,    length: 1 },
      { midi: 65, hand: 'R', beat: 3,    length: 1 },
      { midi: 64, hand: 'R', beat: 4,    length: 2 },
      // Joyeux anniversaire (sol-sol-la-fa-mi-mi-mi)
      { midi: 60, hand: 'R', beat: 6,    length: 0.75 },
      { midi: 60, hand: 'R', beat: 6.75, length: 0.25 },
      { midi: 62, hand: 'R', beat: 7,    length: 1 },
      { midi: 60, hand: 'R', beat: 8,    length: 1 },
      { midi: 67, hand: 'R', beat: 9,    length: 1 },
      { midi: 65, hand: 'R', beat: 10,   length: 2 },
      // Joyeux anniversaire Maxime
      { midi: 60, hand: 'R', beat: 12,    length: 0.75 },
      { midi: 60, hand: 'R', beat: 12.75, length: 0.25 },
      { midi: 72, hand: 'R', beat: 13,    length: 1 },
      { midi: 69, hand: 'R', beat: 14,    length: 1 },
      { midi: 65, hand: 'R', beat: 15,    length: 1 },
      { midi: 64, hand: 'R', beat: 16,    length: 1 },
      { midi: 62, hand: 'R', beat: 17,    length: 1 },
      // Joyeux anniversaire (final)
      { midi: 70, hand: 'R', beat: 18,    length: 0.75 },
      { midi: 70, hand: 'R', beat: 18.75, length: 0.25 },
      { midi: 69, hand: 'R', beat: 19,    length: 1 },
      { midi: 65, hand: 'R', beat: 20,    length: 1 },
      { midi: 67, hand: 'R', beat: 21,    length: 1 },
      { midi: 65, hand: 'R', beat: 22,    length: 4 },
      // Reprise
      { midi: 60, hand: 'R', beat: 28,    length: 0.75 },
      { midi: 60, hand: 'R', beat: 28.75, length: 0.25 },
      { midi: 62, hand: 'R', beat: 29,    length: 1 },
      { midi: 60, hand: 'R', beat: 30,    length: 1 },
      { midi: 65, hand: 'R', beat: 31,    length: 1 },
      { midi: 64, hand: 'R', beat: 32,    length: 2 },
      { midi: 60, hand: 'R', beat: 34,    length: 0.75 },
      { midi: 60, hand: 'R', beat: 34.75, length: 0.25 },
      { midi: 62, hand: 'R', beat: 35,    length: 1 },
      { midi: 60, hand: 'R', beat: 36,    length: 1 },
      { midi: 67, hand: 'R', beat: 37,    length: 1 },
      { midi: 65, hand: 'R', beat: 38,    length: 4 },
      // Basse simple : F – F – C – C – F – F – Bb – F
      { midi: 53, hand: 'L', beat: 0,  length: 4 },
      { midi: 53, hand: 'L', beat: 4,  length: 4 },
      { midi: 48, hand: 'L', beat: 8,  length: 4 },
      { midi: 48, hand: 'L', beat: 12, length: 4 },
      { midi: 53, hand: 'L', beat: 16, length: 4 },
      { midi: 53, hand: 'L', beat: 20, length: 4 },
      { midi: 58, hand: 'L', beat: 24, length: 4 },
      { midi: 53, hand: 'L', beat: 28, length: 4 },
      { midi: 53, hand: 'L', beat: 32, length: 4 },
      { midi: 48, hand: 'L', beat: 36, length: 4 },
      { midi: 53, hand: 'L', beat: 40, length: 2 },
    ],
  },

  // ----------------------------- MEDIUM -----------------------------
  {
    id: 'ode-joie',
    title: 'Ode à la joie',
    difficulty: 'medium',
    bpm: 110,
    notes: [
      // A
      { midi: 64, hand: 'R', beat: 0,  length: 1 },
      { midi: 64, hand: 'R', beat: 1,  length: 1 },
      { midi: 65, hand: 'R', beat: 2,  length: 1 },
      { midi: 67, hand: 'R', beat: 3,  length: 1 },
      { midi: 67, hand: 'R', beat: 4,  length: 1 },
      { midi: 65, hand: 'R', beat: 5,  length: 1 },
      { midi: 64, hand: 'R', beat: 6,  length: 1 },
      { midi: 62, hand: 'R', beat: 7,  length: 1 },
      { midi: 60, hand: 'R', beat: 8,  length: 1 },
      { midi: 60, hand: 'R', beat: 9,  length: 1 },
      { midi: 62, hand: 'R', beat: 10, length: 1 },
      { midi: 64, hand: 'R', beat: 11, length: 1 },
      { midi: 64, hand: 'R', beat: 12, length: 1.5 },
      { midi: 62, hand: 'R', beat: 13.5, length: 0.5 },
      { midi: 62, hand: 'R', beat: 14, length: 2 },
      // A (répétition)
      { midi: 64, hand: 'R', beat: 16, length: 1 },
      { midi: 64, hand: 'R', beat: 17, length: 1 },
      { midi: 65, hand: 'R', beat: 18, length: 1 },
      { midi: 67, hand: 'R', beat: 19, length: 1 },
      { midi: 67, hand: 'R', beat: 20, length: 1 },
      { midi: 65, hand: 'R', beat: 21, length: 1 },
      { midi: 64, hand: 'R', beat: 22, length: 1 },
      { midi: 62, hand: 'R', beat: 23, length: 1 },
      { midi: 60, hand: 'R', beat: 24, length: 1 },
      { midi: 60, hand: 'R', beat: 25, length: 1 },
      { midi: 62, hand: 'R', beat: 26, length: 1 },
      { midi: 64, hand: 'R', beat: 27, length: 1 },
      { midi: 62, hand: 'R', beat: 28, length: 1.5 },
      { midi: 60, hand: 'R', beat: 29.5, length: 0.5 },
      { midi: 60, hand: 'R', beat: 30, length: 2 },
      // B — pont
      { midi: 62, hand: 'R', beat: 32, length: 1 },
      { midi: 62, hand: 'R', beat: 33, length: 1 },
      { midi: 64, hand: 'R', beat: 34, length: 1 },
      { midi: 60, hand: 'R', beat: 35, length: 1 },
      { midi: 62, hand: 'R', beat: 36, length: 1 },
      { midi: 64, hand: 'R', beat: 37, length: 0.5 },
      { midi: 65, hand: 'R', beat: 37.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 38, length: 1 },
      { midi: 60, hand: 'R', beat: 39, length: 1 },
      { midi: 62, hand: 'R', beat: 40, length: 1 },
      { midi: 64, hand: 'R', beat: 41, length: 0.5 },
      { midi: 65, hand: 'R', beat: 41.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 42, length: 1 },
      { midi: 62, hand: 'R', beat: 43, length: 1 },
      { midi: 60, hand: 'R', beat: 44, length: 1 },
      { midi: 62, hand: 'R', beat: 45, length: 1 },
      { midi: 55, hand: 'R', beat: 46, length: 2 },
      // A (final)
      { midi: 64, hand: 'R', beat: 48, length: 1 },
      { midi: 64, hand: 'R', beat: 49, length: 1 },
      { midi: 65, hand: 'R', beat: 50, length: 1 },
      { midi: 67, hand: 'R', beat: 51, length: 1 },
      { midi: 67, hand: 'R', beat: 52, length: 1 },
      { midi: 65, hand: 'R', beat: 53, length: 1 },
      { midi: 64, hand: 'R', beat: 54, length: 1 },
      { midi: 62, hand: 'R', beat: 55, length: 1 },
      { midi: 60, hand: 'R', beat: 56, length: 1 },
      { midi: 60, hand: 'R', beat: 57, length: 1 },
      { midi: 62, hand: 'R', beat: 58, length: 1 },
      { midi: 64, hand: 'R', beat: 59, length: 1 },
      { midi: 62, hand: 'R', beat: 60, length: 1.5 },
      { midi: 60, hand: 'R', beat: 61.5, length: 0.5 },
      { midi: 60, hand: 'R', beat: 62, length: 2 },
      // Basse
      { midi: 48, hand: 'L', beat: 0,  length: 2 },
      { midi: 55, hand: 'L', beat: 2,  length: 2 },
      { midi: 48, hand: 'L', beat: 4,  length: 2 },
      { midi: 55, hand: 'L', beat: 6,  length: 2 },
      { midi: 53, hand: 'L', beat: 8,  length: 2 },
      { midi: 55, hand: 'L', beat: 10, length: 2 },
      { midi: 48, hand: 'L', beat: 12, length: 2 },
      { midi: 55, hand: 'L', beat: 14, length: 2 },
      { midi: 48, hand: 'L', beat: 16, length: 2 },
      { midi: 55, hand: 'L', beat: 18, length: 2 },
      { midi: 48, hand: 'L', beat: 20, length: 2 },
      { midi: 55, hand: 'L', beat: 22, length: 2 },
      { midi: 53, hand: 'L', beat: 24, length: 2 },
      { midi: 55, hand: 'L', beat: 26, length: 2 },
      { midi: 48, hand: 'L', beat: 28, length: 4 },
      { midi: 50, hand: 'L', beat: 32, length: 2 },
      { midi: 57, hand: 'L', beat: 34, length: 2 },
      { midi: 50, hand: 'L', beat: 36, length: 2 },
      { midi: 57, hand: 'L', beat: 38, length: 2 },
      { midi: 50, hand: 'L', beat: 40, length: 2 },
      { midi: 57, hand: 'L', beat: 42, length: 2 },
      { midi: 50, hand: 'L', beat: 44, length: 2 },
      { midi: 55, hand: 'L', beat: 46, length: 2 },
      { midi: 48, hand: 'L', beat: 48, length: 2 },
      { midi: 55, hand: 'L', beat: 50, length: 2 },
      { midi: 48, hand: 'L', beat: 52, length: 2 },
      { midi: 55, hand: 'L', beat: 54, length: 2 },
      { midi: 53, hand: 'L', beat: 56, length: 2 },
      { midi: 55, hand: 'L', beat: 58, length: 2 },
      { midi: 48, hand: 'L', beat: 60, length: 4 },
    ],
  },

  {
    id: 'pachelbel',
    title: 'Canon de Pachelbel (simplifié)',
    difficulty: 'medium',
    bpm: 80,
    notes: [
      // Mélodie main droite — variation simple sur la grille D-A-B-F#-G-D-G-A
      // (transposée en Do : C G Am Em F C F G)
      { midi: 64, hand: 'R', beat: 0,  length: 2 },
      { midi: 62, hand: 'R', beat: 2,  length: 2 },
      { midi: 60, hand: 'R', beat: 4,  length: 2 },
      { midi: 59, hand: 'R', beat: 6,  length: 2 },
      { midi: 57, hand: 'R', beat: 8,  length: 2 },
      { midi: 55, hand: 'R', beat: 10, length: 2 },
      { midi: 57, hand: 'R', beat: 12, length: 2 },
      { midi: 59, hand: 'R', beat: 14, length: 2 },
      // 2e tour avec mouvement
      { midi: 60, hand: 'R', beat: 16, length: 1 },
      { midi: 64, hand: 'R', beat: 17, length: 1 },
      { midi: 62, hand: 'R', beat: 18, length: 1 },
      { midi: 59, hand: 'R', beat: 19, length: 1 },
      { midi: 60, hand: 'R', beat: 20, length: 1 },
      { midi: 64, hand: 'R', beat: 21, length: 1 },
      { midi: 60, hand: 'R', beat: 22, length: 1 },
      { midi: 59, hand: 'R', beat: 23, length: 1 },
      { midi: 57, hand: 'R', beat: 24, length: 1 },
      { midi: 60, hand: 'R', beat: 25, length: 1 },
      { midi: 59, hand: 'R', beat: 26, length: 1 },
      { midi: 55, hand: 'R', beat: 27, length: 1 },
      { midi: 57, hand: 'R', beat: 28, length: 1 },
      { midi: 60, hand: 'R', beat: 29, length: 1 },
      { midi: 59, hand: 'R', beat: 30, length: 1 },
      { midi: 62, hand: 'R', beat: 31, length: 1 },
      // 3e tour — croches descendantes
      { midi: 64, hand: 'R', beat: 32, length: 0.5 },
      { midi: 65, hand: 'R', beat: 32.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 33, length: 0.5 },
      { midi: 62, hand: 'R', beat: 33.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 34, length: 0.5 },
      { midi: 60, hand: 'R', beat: 34.5, length: 0.5 },
      { midi: 62, hand: 'R', beat: 35, length: 0.5 },
      { midi: 64, hand: 'R', beat: 35.5, length: 0.5 },
      { midi: 65, hand: 'R', beat: 36, length: 0.5 },
      { midi: 64, hand: 'R', beat: 36.5, length: 0.5 },
      { midi: 62, hand: 'R', beat: 37, length: 0.5 },
      { midi: 60, hand: 'R', beat: 37.5, length: 0.5 },
      { midi: 62, hand: 'R', beat: 38, length: 0.5 },
      { midi: 60, hand: 'R', beat: 38.5, length: 0.5 },
      { midi: 59, hand: 'R', beat: 39, length: 0.5 },
      { midi: 60, hand: 'R', beat: 39.5, length: 0.5 },
      { midi: 62, hand: 'R', beat: 40, length: 0.5 },
      { midi: 60, hand: 'R', beat: 40.5, length: 0.5 },
      { midi: 59, hand: 'R', beat: 41, length: 0.5 },
      { midi: 57, hand: 'R', beat: 41.5, length: 0.5 },
      { midi: 59, hand: 'R', beat: 42, length: 0.5 },
      { midi: 57, hand: 'R', beat: 42.5, length: 0.5 },
      { midi: 55, hand: 'R', beat: 43, length: 0.5 },
      { midi: 57, hand: 'R', beat: 43.5, length: 0.5 },
      { midi: 59, hand: 'R', beat: 44, length: 0.5 },
      { midi: 60, hand: 'R', beat: 44.5, length: 0.5 },
      { midi: 62, hand: 'R', beat: 45, length: 0.5 },
      { midi: 64, hand: 'R', beat: 45.5, length: 0.5 },
      { midi: 65, hand: 'R', beat: 46, length: 1 },
      { midi: 67, hand: 'R', beat: 47, length: 1 },
      // Conclusion
      { midi: 64, hand: 'R', beat: 48, length: 4 },
      // Basse — Canon : C G Am Em F C F G (8 mesures de 2 temps)
      { midi: 48, hand: 'L', beat: 0,  length: 2 },
      { midi: 55, hand: 'L', beat: 2,  length: 2 },
      { midi: 57, hand: 'L', beat: 4,  length: 2 },
      { midi: 52, hand: 'L', beat: 6,  length: 2 },
      { midi: 53, hand: 'L', beat: 8,  length: 2 },
      { midi: 48, hand: 'L', beat: 10, length: 2 },
      { midi: 53, hand: 'L', beat: 12, length: 2 },
      { midi: 55, hand: 'L', beat: 14, length: 2 },
      { midi: 48, hand: 'L', beat: 16, length: 2 },
      { midi: 55, hand: 'L', beat: 18, length: 2 },
      { midi: 57, hand: 'L', beat: 20, length: 2 },
      { midi: 52, hand: 'L', beat: 22, length: 2 },
      { midi: 53, hand: 'L', beat: 24, length: 2 },
      { midi: 48, hand: 'L', beat: 26, length: 2 },
      { midi: 53, hand: 'L', beat: 28, length: 2 },
      { midi: 55, hand: 'L', beat: 30, length: 2 },
      { midi: 48, hand: 'L', beat: 32, length: 2 },
      { midi: 55, hand: 'L', beat: 34, length: 2 },
      { midi: 57, hand: 'L', beat: 36, length: 2 },
      { midi: 52, hand: 'L', beat: 38, length: 2 },
      { midi: 53, hand: 'L', beat: 40, length: 2 },
      { midi: 48, hand: 'L', beat: 42, length: 2 },
      { midi: 53, hand: 'L', beat: 44, length: 2 },
      { midi: 55, hand: 'L', beat: 46, length: 2 },
      { midi: 48, hand: 'L', beat: 48, length: 4 },
    ],
  },

  {
    id: 'amazing-grace',
    title: 'Amazing Grace',
    difficulty: 'medium',
    bpm: 75,
    notes: [
      // 3/4 time — A-mazing grace, how sweet the sound
      { midi: 60, hand: 'R', beat: 0,  length: 2 },
      { midi: 65, hand: 'R', beat: 2,  length: 1 },
      { midi: 64, hand: 'R', beat: 3,  length: 2 },
      { midi: 65, hand: 'R', beat: 5,  length: 1 },
      { midi: 64, hand: 'R', beat: 6,  length: 2 },
      { midi: 60, hand: 'R', beat: 8,  length: 1 },
      { midi: 57, hand: 'R', beat: 9,  length: 2 },
      { midi: 60, hand: 'R', beat: 11, length: 1 },
      { midi: 60, hand: 'R', beat: 12, length: 3 },
      // That saved a wretch like me
      { midi: 64, hand: 'R', beat: 15, length: 2 },
      { midi: 65, hand: 'R', beat: 17, length: 1 },
      { midi: 64, hand: 'R', beat: 18, length: 2 },
      { midi: 65, hand: 'R', beat: 20, length: 1 },
      { midi: 67, hand: 'R', beat: 21, length: 6 },
      // I once was lost but now am found
      { midi: 67, hand: 'R', beat: 27, length: 2 },
      { midi: 64, hand: 'R', beat: 29, length: 1 },
      { midi: 60, hand: 'R', beat: 30, length: 2 },
      { midi: 64, hand: 'R', beat: 32, length: 1 },
      { midi: 62, hand: 'R', beat: 33, length: 2 },
      { midi: 60, hand: 'R', beat: 35, length: 1 },
      { midi: 57, hand: 'R', beat: 36, length: 3 },
      { midi: 60, hand: 'R', beat: 39, length: 3 },
      // Was blind but now I see
      { midi: 64, hand: 'R', beat: 42, length: 2 },
      { midi: 65, hand: 'R', beat: 44, length: 1 },
      { midi: 64, hand: 'R', beat: 45, length: 2 },
      { midi: 65, hand: 'R', beat: 47, length: 1 },
      { midi: 64, hand: 'R', beat: 48, length: 2 },
      { midi: 60, hand: 'R', beat: 50, length: 1 },
      { midi: 57, hand: 'R', beat: 51, length: 2 },
      { midi: 60, hand: 'R', beat: 53, length: 1 },
      { midi: 60, hand: 'R', beat: 54, length: 6 },
      // Basse — F – F – C – F – Bb – F – C – F (mesures de 3 temps)
      { midi: 53, hand: 'L', beat: 0,  length: 3 },
      { midi: 53, hand: 'L', beat: 3,  length: 3 },
      { midi: 48, hand: 'L', beat: 6,  length: 3 },
      { midi: 48, hand: 'L', beat: 9,  length: 3 },
      { midi: 53, hand: 'L', beat: 12, length: 3 },
      { midi: 53, hand: 'L', beat: 15, length: 3 },
      { midi: 58, hand: 'L', beat: 18, length: 3 },
      { midi: 48, hand: 'L', beat: 21, length: 3 },
      { midi: 53, hand: 'L', beat: 24, length: 3 },
      { midi: 50, hand: 'L', beat: 27, length: 3 },
      { midi: 48, hand: 'L', beat: 30, length: 3 },
      { midi: 53, hand: 'L', beat: 33, length: 3 },
      { midi: 50, hand: 'L', beat: 36, length: 3 },
      { midi: 48, hand: 'L', beat: 39, length: 3 },
      { midi: 53, hand: 'L', beat: 42, length: 3 },
      { midi: 53, hand: 'L', beat: 45, length: 3 },
      { midi: 58, hand: 'L', beat: 48, length: 3 },
      { midi: 48, hand: 'L', beat: 51, length: 3 },
      { midi: 53, hand: 'L', beat: 54, length: 6 },
    ],
  },

  // ----------------------------- HARD -----------------------------
  {
    id: 'fur-elise',
    title: 'Für Elise (thème complet)',
    difficulty: 'hard',
    bpm: 72,
    notes: [
      // Thème A
      { midi: 64, hand: 'R', beat: 0,    length: 0.5 },
      { midi: 63, hand: 'R', beat: 0.5,  length: 0.5 },
      { midi: 64, hand: 'R', beat: 1,    length: 0.5 },
      { midi: 63, hand: 'R', beat: 1.5,  length: 0.5 },
      { midi: 64, hand: 'R', beat: 2,    length: 0.5 },
      { midi: 59, hand: 'R', beat: 2.5,  length: 0.5 },
      { midi: 62, hand: 'R', beat: 3,    length: 0.5 },
      { midi: 60, hand: 'R', beat: 3.5,  length: 0.5 },
      { midi: 57, hand: 'R', beat: 4,    length: 1.5 },
      { midi: 48, hand: 'L', beat: 4,    length: 0.5 },
      { midi: 52, hand: 'L', beat: 4.5,  length: 0.5 },
      { midi: 57, hand: 'L', beat: 5,    length: 0.5 },
      { midi: 59, hand: 'R', beat: 5.5,  length: 0.5 },
      { midi: 60, hand: 'R', beat: 6,    length: 0.5 },
      { midi: 64, hand: 'R', beat: 6.5,  length: 0.5 },
      { midi: 52, hand: 'L', beat: 7,    length: 0.5 },
      { midi: 56, hand: 'L', beat: 7.5,  length: 0.5 },
      { midi: 59, hand: 'L', beat: 8,    length: 0.5 },
      { midi: 60, hand: 'R', beat: 8.5,  length: 1.5 },
      // Reprise du thème A
      { midi: 64, hand: 'R', beat: 10,   length: 0.5 },
      { midi: 52, hand: 'L', beat: 10,   length: 0.5 },
      { midi: 57, hand: 'L', beat: 10.5, length: 0.5 },
      { midi: 60, hand: 'L', beat: 11,   length: 0.5 },
      { midi: 64, hand: 'R', beat: 11.5, length: 0.5 },
      { midi: 63, hand: 'R', beat: 12,   length: 0.5 },
      { midi: 64, hand: 'R', beat: 12.5, length: 0.5 },
      { midi: 63, hand: 'R', beat: 13,   length: 0.5 },
      { midi: 64, hand: 'R', beat: 13.5, length: 0.5 },
      { midi: 59, hand: 'R', beat: 14,   length: 0.5 },
      { midi: 62, hand: 'R', beat: 14.5, length: 0.5 },
      { midi: 60, hand: 'R', beat: 15,   length: 0.5 },
      { midi: 57, hand: 'R', beat: 15.5, length: 1.5 },
      { midi: 48, hand: 'L', beat: 15.5, length: 0.5 },
      { midi: 52, hand: 'L', beat: 16,   length: 0.5 },
      { midi: 57, hand: 'L', beat: 16.5, length: 0.5 },
      { midi: 59, hand: 'R', beat: 17,   length: 0.5 },
      { midi: 60, hand: 'R', beat: 17.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 18,   length: 0.5 },
      { midi: 52, hand: 'L', beat: 18.5, length: 0.5 },
      { midi: 56, hand: 'L', beat: 19,   length: 0.5 },
      { midi: 59, hand: 'L', beat: 19.5, length: 0.5 },
      { midi: 60, hand: 'R', beat: 20,   length: 1 },
      { midi: 57, hand: 'R', beat: 21,   length: 1 },
      // Section B — vers le motif central
      { midi: 67, hand: 'R', beat: 22,   length: 0.5 },
      { midi: 65, hand: 'R', beat: 22.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 23,   length: 0.5 },
      { midi: 50, hand: 'L', beat: 23,   length: 0.5 },
      { midi: 57, hand: 'L', beat: 23.5, length: 0.5 },
      { midi: 60, hand: 'L', beat: 24,   length: 0.5 },
      { midi: 65, hand: 'R', beat: 24.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 25,   length: 0.5 },
      { midi: 62, hand: 'R', beat: 25.5, length: 0.5 },
      { midi: 65, hand: 'R', beat: 26,   length: 0.5 },
      { midi: 52, hand: 'L', beat: 26,   length: 0.5 },
      { midi: 60, hand: 'L', beat: 26.5, length: 0.5 },
      { midi: 64, hand: 'L', beat: 27,   length: 0.5 },
      { midi: 64, hand: 'R', beat: 27.5, length: 0.5 },
      { midi: 62, hand: 'R', beat: 28,   length: 0.5 },
      { midi: 60, hand: 'R', beat: 28.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 29,   length: 0.5 },
      { midi: 52, hand: 'L', beat: 29,   length: 0.5 },
      { midi: 59, hand: 'L', beat: 29.5, length: 0.5 },
      { midi: 64, hand: 'L', beat: 30,   length: 0.5 },
      { midi: 63, hand: 'R', beat: 30.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 31,   length: 1 },
      // Retour au thème A (final)
      { midi: 64, hand: 'R', beat: 32,   length: 0.5 },
      { midi: 63, hand: 'R', beat: 32.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 33,   length: 0.5 },
      { midi: 63, hand: 'R', beat: 33.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 34,   length: 0.5 },
      { midi: 59, hand: 'R', beat: 34.5, length: 0.5 },
      { midi: 62, hand: 'R', beat: 35,   length: 0.5 },
      { midi: 60, hand: 'R', beat: 35.5, length: 0.5 },
      { midi: 57, hand: 'R', beat: 36,   length: 1.5 },
      { midi: 48, hand: 'L', beat: 36,   length: 0.5 },
      { midi: 52, hand: 'L', beat: 36.5, length: 0.5 },
      { midi: 57, hand: 'L', beat: 37,   length: 0.5 },
      { midi: 59, hand: 'R', beat: 37.5, length: 0.5 },
      { midi: 60, hand: 'R', beat: 38,   length: 0.5 },
      { midi: 64, hand: 'R', beat: 38.5, length: 0.5 },
      { midi: 52, hand: 'L', beat: 39,   length: 0.5 },
      { midi: 56, hand: 'L', beat: 39.5, length: 0.5 },
      { midi: 59, hand: 'L', beat: 40,   length: 0.5 },
      { midi: 60, hand: 'R', beat: 40.5, length: 1.5 },
      { midi: 57, hand: 'R', beat: 42,   length: 2 },
    ],
  },

  {
    id: 'prelude-c-bach',
    title: 'Prélude en Do (Bach BWV 846)',
    difficulty: 'hard',
    bpm: 70,
    notes: [
      // Mesure 1 : C E G C E (motif x2)
      { midi: 48, hand: 'L', beat: 0,    length: 0.5 },
      { midi: 52, hand: 'L', beat: 0.5,  length: 0.5 },
      { midi: 55, hand: 'R', beat: 1,    length: 0.5 },
      { midi: 60, hand: 'R', beat: 1.5,  length: 0.5 },
      { midi: 64, hand: 'R', beat: 2,    length: 0.5 },
      { midi: 55, hand: 'R', beat: 2.5,  length: 0.5 },
      { midi: 60, hand: 'R', beat: 3,    length: 0.5 },
      { midi: 64, hand: 'R', beat: 3.5,  length: 0.5 },
      // Mesure 2 : C D A D F
      { midi: 48, hand: 'L', beat: 4,    length: 0.5 },
      { midi: 50, hand: 'L', beat: 4.5,  length: 0.5 },
      { midi: 57, hand: 'R', beat: 5,    length: 0.5 },
      { midi: 62, hand: 'R', beat: 5.5,  length: 0.5 },
      { midi: 65, hand: 'R', beat: 6,    length: 0.5 },
      { midi: 57, hand: 'R', beat: 6.5,  length: 0.5 },
      { midi: 62, hand: 'R', beat: 7,    length: 0.5 },
      { midi: 65, hand: 'R', beat: 7.5,  length: 0.5 },
      // Mesure 3 : B D G D F (B = 47 hors clavier ; on monte d'octave : B3 = 59)
      { midi: 48, hand: 'L', beat: 8,    length: 0.5 },
      { midi: 50, hand: 'L', beat: 8.5,  length: 0.5 },
      { midi: 55, hand: 'R', beat: 9,    length: 0.5 },
      { midi: 59, hand: 'R', beat: 9.5,  length: 0.5 },
      { midi: 65, hand: 'R', beat: 10,   length: 0.5 },
      { midi: 55, hand: 'R', beat: 10.5, length: 0.5 },
      { midi: 59, hand: 'R', beat: 11,   length: 0.5 },
      { midi: 65, hand: 'R', beat: 11.5, length: 0.5 },
      // Mesure 4 : C E G C E
      { midi: 48, hand: 'L', beat: 12,   length: 0.5 },
      { midi: 52, hand: 'L', beat: 12.5, length: 0.5 },
      { midi: 55, hand: 'R', beat: 13,   length: 0.5 },
      { midi: 60, hand: 'R', beat: 13.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 14,   length: 0.5 },
      { midi: 55, hand: 'R', beat: 14.5, length: 0.5 },
      { midi: 60, hand: 'R', beat: 15,   length: 0.5 },
      { midi: 64, hand: 'R', beat: 15.5, length: 0.5 },
      // Mesure 5 : C E A E A
      { midi: 48, hand: 'L', beat: 16,   length: 0.5 },
      { midi: 52, hand: 'L', beat: 16.5, length: 0.5 },
      { midi: 57, hand: 'R', beat: 17,   length: 0.5 },
      { midi: 60, hand: 'R', beat: 17.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 18,   length: 0.5 },
      { midi: 57, hand: 'R', beat: 18.5, length: 0.5 },
      { midi: 60, hand: 'R', beat: 19,   length: 0.5 },
      { midi: 64, hand: 'R', beat: 19.5, length: 0.5 },
      // Mesure 6 : C D F# A D
      { midi: 48, hand: 'L', beat: 20,   length: 0.5 },
      { midi: 50, hand: 'L', beat: 20.5, length: 0.5 },
      { midi: 54, hand: 'R', beat: 21,   length: 0.5 },
      { midi: 57, hand: 'R', beat: 21.5, length: 0.5 },
      { midi: 62, hand: 'R', beat: 22,   length: 0.5 },
      { midi: 54, hand: 'R', beat: 22.5, length: 0.5 },
      { midi: 57, hand: 'R', beat: 23,   length: 0.5 },
      { midi: 62, hand: 'R', beat: 23.5, length: 0.5 },
      // Mesure 7 : G D G B F
      { midi: 55, hand: 'L', beat: 24,   length: 0.5 },
      { midi: 50, hand: 'L', beat: 24.5, length: 0.5 },
      { midi: 55, hand: 'R', beat: 25,   length: 0.5 },
      { midi: 59, hand: 'R', beat: 25.5, length: 0.5 },
      { midi: 65, hand: 'R', beat: 26,   length: 0.5 },
      { midi: 55, hand: 'R', beat: 26.5, length: 0.5 },
      { midi: 59, hand: 'R', beat: 27,   length: 0.5 },
      { midi: 65, hand: 'R', beat: 27.5, length: 0.5 },
      // Mesure 8 : G E G C E
      { midi: 55, hand: 'L', beat: 28,   length: 0.5 },
      { midi: 52, hand: 'L', beat: 28.5, length: 0.5 },
      { midi: 55, hand: 'R', beat: 29,   length: 0.5 },
      { midi: 60, hand: 'R', beat: 29.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 30,   length: 0.5 },
      { midi: 55, hand: 'R', beat: 30.5, length: 0.5 },
      { midi: 60, hand: 'R', beat: 31,   length: 0.5 },
      { midi: 64, hand: 'R', beat: 31.5, length: 0.5 },
      // Conclusion sur Do
      { midi: 48, hand: 'L', beat: 32,   length: 4 },
      { midi: 60, hand: 'R', beat: 32,   length: 4 },
      { midi: 64, hand: 'R', beat: 32,   length: 4 },
      { midi: 67, hand: 'R', beat: 32,   length: 4 },
    ],
  },

  {
    id: 'greensleeves',
    title: 'Greensleeves',
    difficulty: 'hard',
    bpm: 90,
    notes: [
      // 6/8 — Alas my love (en La mineur)
      { midi: 57, hand: 'R', beat: 0,    length: 1.5 },
      { midi: 60, hand: 'R', beat: 1.5,  length: 1 },
      { midi: 62, hand: 'R', beat: 2.5,  length: 0.5 },
      { midi: 64, hand: 'R', beat: 3,    length: 1 },
      { midi: 65, hand: 'R', beat: 4,    length: 0.5 },
      { midi: 64, hand: 'R', beat: 4.5,  length: 1 },
      { midi: 62, hand: 'R', beat: 5.5,  length: 0.5 },
      { midi: 59, hand: 'R', beat: 6,    length: 1.5 },
      { midi: 55, hand: 'R', beat: 7.5,  length: 1 },
      { midi: 57, hand: 'R', beat: 8.5,  length: 0.5 },
      { midi: 59, hand: 'R', beat: 9,    length: 1 },
      { midi: 60, hand: 'R', beat: 10,   length: 0.5 },
      { midi: 57, hand: 'R', beat: 10.5, length: 1.5 },
      { midi: 57, hand: 'R', beat: 12,   length: 1 },
      { midi: 56, hand: 'R', beat: 13,   length: 0.5 },
      { midi: 57, hand: 'R', beat: 13.5, length: 1 },
      { midi: 59, hand: 'R', beat: 14.5, length: 0.5 },
      { midi: 60, hand: 'R', beat: 15,   length: 3 },
      // 2e moitié — la chord (E)
      { midi: 57, hand: 'R', beat: 18,   length: 1.5 },
      { midi: 60, hand: 'R', beat: 19.5, length: 1 },
      { midi: 62, hand: 'R', beat: 20.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 21,   length: 1 },
      { midi: 65, hand: 'R', beat: 22,   length: 0.5 },
      { midi: 64, hand: 'R', beat: 22.5, length: 1 },
      { midi: 62, hand: 'R', beat: 23.5, length: 0.5 },
      { midi: 59, hand: 'R', beat: 24,   length: 1.5 },
      { midi: 55, hand: 'R', beat: 25.5, length: 1 },
      { midi: 57, hand: 'R', beat: 26.5, length: 0.5 },
      { midi: 59, hand: 'R', beat: 27,   length: 1 },
      { midi: 60, hand: 'R', beat: 28,   length: 0.5 },
      { midi: 59, hand: 'R', beat: 28.5, length: 1 },
      { midi: 56, hand: 'R', beat: 29.5, length: 0.5 },
      { midi: 56, hand: 'R', beat: 30,   length: 1.5 },
      { midi: 57, hand: 'R', beat: 31.5, length: 4.5 },
      // Refrain — Greensleeves was all my joy (octave aiguë)
      { midi: 69, hand: 'R', beat: 36,   length: 1.5 },
      { midi: 69, hand: 'R', beat: 37.5, length: 1 },
      { midi: 68, hand: 'R', beat: 38.5, length: 0.5 },
      { midi: 69, hand: 'R', beat: 39,   length: 1 },
      { midi: 71, hand: 'R', beat: 40,   length: 0.5 },
      { midi: 72, hand: 'R', beat: 40.5, length: 3 },
      { midi: 71, hand: 'R', beat: 43.5, length: 1 },
      { midi: 69, hand: 'R', beat: 44.5, length: 0.5 },
      { midi: 67, hand: 'R', beat: 45,   length: 1.5 },
      { midi: 64, hand: 'R', beat: 46.5, length: 1 },
      { midi: 65, hand: 'R', beat: 47.5, length: 0.5 },
      { midi: 67, hand: 'R', beat: 48,   length: 1 },
      { midi: 69, hand: 'R', beat: 49,   length: 0.5 },
      { midi: 65, hand: 'R', beat: 49.5, length: 1.5 },
      { midi: 65, hand: 'R', beat: 51,   length: 1 },
      { midi: 64, hand: 'R', beat: 52,   length: 0.5 },
      { midi: 65, hand: 'R', beat: 52.5, length: 1 },
      { midi: 67, hand: 'R', beat: 53.5, length: 0.5 },
      { midi: 64, hand: 'R', beat: 54,   length: 4.5 },
      // Basse — Am Am G G F F C E (par mesure de 3 temps)
      { midi: 57, hand: 'L', beat: 0,    length: 3 },
      { midi: 57, hand: 'L', beat: 3,    length: 3 },
      { midi: 55, hand: 'L', beat: 6,    length: 3 },
      { midi: 55, hand: 'L', beat: 9,    length: 3 },
      { midi: 53, hand: 'L', beat: 12,   length: 3 },
      { midi: 52, hand: 'L', beat: 15,   length: 3 },
      { midi: 57, hand: 'L', beat: 18,   length: 3 },
      { midi: 57, hand: 'L', beat: 21,   length: 3 },
      { midi: 55, hand: 'L', beat: 24,   length: 3 },
      { midi: 55, hand: 'L', beat: 27,   length: 3 },
      { midi: 52, hand: 'L', beat: 30,   length: 3 },
      { midi: 57, hand: 'L', beat: 33,   length: 3 },
      { midi: 53, hand: 'L', beat: 36,   length: 3 },
      { midi: 53, hand: 'L', beat: 39,   length: 3 },
      { midi: 48, hand: 'L', beat: 42,   length: 3 },
      { midi: 55, hand: 'L', beat: 45,   length: 3 },
      { midi: 53, hand: 'L', beat: 48,   length: 3 },
      { midi: 48, hand: 'L', beat: 51,   length: 3 },
      { midi: 57, hand: 'L', beat: 54,   length: 4.5 },
    ],
  },
  // ----------------------------- VERY EASY (additions) -----------------------------
  {
    id: 'hot-cross-buns',
    title: 'Hot Cross Buns',
    difficulty: 'very-easy',
    bpm: 100,
    notes: [
      // Mi Ré Do
      { midi: 64, hand: 'R', beat: 0, length: 1 },
      { midi: 62, hand: 'R', beat: 1, length: 1 },
      { midi: 60, hand: 'R', beat: 2, length: 2 },
      // Mi Ré Do
      { midi: 64, hand: 'R', beat: 4, length: 1 },
      { midi: 62, hand: 'R', beat: 5, length: 1 },
      { midi: 60, hand: 'R', beat: 6, length: 2 },
      // Do Do Do Do — Ré Ré Ré Ré
      { midi: 60, hand: 'R', beat: 8,  length: 0.5 },
      { midi: 60, hand: 'R', beat: 8.5, length: 0.5 },
      { midi: 60, hand: 'R', beat: 9,  length: 0.5 },
      { midi: 60, hand: 'R', beat: 9.5, length: 0.5 },
      { midi: 62, hand: 'R', beat: 10, length: 0.5 },
      { midi: 62, hand: 'R', beat: 10.5, length: 0.5 },
      { midi: 62, hand: 'R', beat: 11, length: 0.5 },
      { midi: 62, hand: 'R', beat: 11.5, length: 0.5 },
      // Mi Ré Do
      { midi: 64, hand: 'R', beat: 12, length: 1 },
      { midi: 62, hand: 'R', beat: 13, length: 1 },
      { midi: 60, hand: 'R', beat: 14, length: 2 },
    ],
  },

];

window.SONGS = SONGS;
