// Songs: { id, title, difficulty, bpm, notes: [{midi, hand, beat, length}] }
// hand: 'R' = right, 'L' = left. beat/length in quarter notes.

const SONGS = [
  {
    id: 'au-clair',
    title: 'Au clair de la lune',
    difficulty: 'very-easy',
    bpm: 90,
    notes: [
      { midi: 60, hand: 'R', beat: 0,  length: 1 },
      { midi: 60, hand: 'R', beat: 1,  length: 1 },
      { midi: 60, hand: 'R', beat: 2,  length: 1 },
      { midi: 62, hand: 'R', beat: 3,  length: 1 },
      { midi: 64, hand: 'R', beat: 4,  length: 2 },
      { midi: 62, hand: 'R', beat: 6,  length: 2 },
      { midi: 60, hand: 'R', beat: 8,  length: 1 },
      { midi: 64, hand: 'R', beat: 9,  length: 1 },
      { midi: 62, hand: 'R', beat: 10, length: 1 },
      { midi: 62, hand: 'R', beat: 11, length: 1 },
      { midi: 60, hand: 'R', beat: 12, length: 4 },
      { midi: 48, hand: 'L', beat: 0,  length: 4 },
      { midi: 48, hand: 'L', beat: 4,  length: 4 },
      { midi: 55, hand: 'L', beat: 8,  length: 4 },
      { midi: 48, hand: 'L', beat: 12, length: 4 },
    ],
  },
  {
    id: 'frere-jacques',
    title: 'Frère Jacques',
    difficulty: 'easy',
    bpm: 110,
    notes: [
      { midi: 60, hand: 'R', beat: 0,  length: 1 },
      { midi: 62, hand: 'R', beat: 1,  length: 1 },
      { midi: 64, hand: 'R', beat: 2,  length: 1 },
      { midi: 60, hand: 'R', beat: 3,  length: 1 },
      { midi: 60, hand: 'R', beat: 4,  length: 1 },
      { midi: 62, hand: 'R', beat: 5,  length: 1 },
      { midi: 64, hand: 'R', beat: 6,  length: 1 },
      { midi: 60, hand: 'R', beat: 7,  length: 1 },
      { midi: 64, hand: 'R', beat: 8,  length: 1 },
      { midi: 65, hand: 'R', beat: 9,  length: 1 },
      { midi: 67, hand: 'R', beat: 10, length: 2 },
      { midi: 64, hand: 'R', beat: 12, length: 1 },
      { midi: 65, hand: 'R', beat: 13, length: 1 },
      { midi: 67, hand: 'R', beat: 14, length: 2 },
      { midi: 48, hand: 'L', beat: 0,  length: 4 },
      { midi: 48, hand: 'L', beat: 4,  length: 4 },
      { midi: 48, hand: 'L', beat: 8,  length: 4 },
      { midi: 48, hand: 'L', beat: 12, length: 4 },
    ],
  },
  {
    id: 'ode-joie',
    title: 'Ode à la joie',
    difficulty: 'medium',
    bpm: 110,
    notes: [
      { midi: 64, hand: 'R', beat: 0,  length: 1 },
      { midi: 64, hand: 'R', beat: 1,  length: 1 },
      { midi: 65, hand: 'R', beat: 2,  length: 1 },
      { midi: 67, hand: 'R', beat: 3,  length: 1 },
      { midi: 67, hand: 'R', beat: 4,  length: 1 },
      { midi: 65, hand: 'R', beat: 5,  length: 1 },
      { midi: 64, hand: 'R', beat: 6,  length: 1 },
      { midi: 62, hand: 'R', beat: 7,  length: 1 },
      { midi: 60, hand: 'R', beat: 8,  length: 1 },
      { midi: 60, hand: 'R', beat: 9,  length: 1 },
      { midi: 62, hand: 'R', beat: 10, length: 1 },
      { midi: 64, hand: 'R', beat: 11, length: 1 },
      { midi: 64, hand: 'R', beat: 12, length: 1.5 },
      { midi: 62, hand: 'R', beat: 13.5, length: 0.5 },
      { midi: 62, hand: 'R', beat: 14, length: 2 },
      { midi: 48, hand: 'L', beat: 0,  length: 2 },
      { midi: 55, hand: 'L', beat: 2,  length: 2 },
      { midi: 48, hand: 'L', beat: 4,  length: 2 },
      { midi: 55, hand: 'L', beat: 6,  length: 2 },
      { midi: 53, hand: 'L', beat: 8,  length: 2 },
      { midi: 55, hand: 'L', beat: 10, length: 2 },
      { midi: 48, hand: 'L', beat: 12, length: 2 },
      { midi: 55, hand: 'L', beat: 14, length: 2 },
    ],
  },
  {
    id: 'fur-elise',
    title: 'Für Elise (intro)',
    difficulty: 'hard',
    bpm: 72,
    notes: [
      { midi: 76, hand: 'R', beat: 0,    length: 0.5 },
      { midi: 75, hand: 'R', beat: 0.5,  length: 0.5 },
      { midi: 76, hand: 'R', beat: 1,    length: 0.5 },
      { midi: 75, hand: 'R', beat: 1.5,  length: 0.5 },
      { midi: 76, hand: 'R', beat: 2,    length: 0.5 },
      { midi: 71, hand: 'R', beat: 2.5,  length: 0.5 },
      { midi: 74, hand: 'R', beat: 3,    length: 0.5 },
      { midi: 72, hand: 'R', beat: 3.5,  length: 0.5 },
      { midi: 69, hand: 'R', beat: 4,    length: 1.5 },
      { midi: 60, hand: 'L', beat: 4,    length: 0.5 },
      { midi: 64, hand: 'L', beat: 4.5,  length: 0.5 },
      { midi: 69, hand: 'L', beat: 5,    length: 0.5 },
      { midi: 71, hand: 'R', beat: 5.5,  length: 0.5 },
      { midi: 72, hand: 'R', beat: 6,    length: 0.5 },
      { midi: 76, hand: 'R', beat: 6.5,  length: 0.5 },
      { midi: 64, hand: 'L', beat: 7,    length: 0.5 },
      { midi: 68, hand: 'L', beat: 7.5,  length: 0.5 },
      { midi: 71, hand: 'L', beat: 8,    length: 0.5 },
      { midi: 72, hand: 'R', beat: 8.5,  length: 1.5 },
    ],
  },
];

window.SONGS = SONGS;
